// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName
import ReactDOM from 'react-dom'
import Header from './Header'
import Home from './Home'

const components = {
  home: Home,
  header: Header,
}

// eslint-disable-next-line no-restricted-syntax
for (const key of Object.keys(components)) {
  const root = ReactDOM.createRoot(document.getElementById(key))
  const component = components[key]()
  root.render(component)
}
